name: Tests

on:
  pull_request:
  workflow_dispatch: {}

jobs:
  pytest:
    name: pytest
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v7

      - name: Install Poetry
        run: pipx install poetry==2.1.3

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run pytest
        run: poetry run pytest
